# Generated by Django 5.2.8 on 2025-11-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_001', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='code',
            field=models.CharField(default='', max_length=20),
        ),
    ]
