# Generated by Django 5.2.8 on 2025-11-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_001', '0004_alter_book_authors_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, help_text='Short biography of the author', max_length=200, null=True),
        ),
    ]
